CPP_SRC  = 	random.cpp observer.cpp observer2.cpp refcount.cpp refcount2.cpp shrink.cpp \
		    string.cpp round.cpp hash.cpp lru.cpp coments.cpp 

ROOT     = ../../..
INCLUDE  =
LIBS     = -lglutm -lglt
                    
default: prog       

include $(ROOT)/gcc/Makefile.inc

