C_SRC    = png.c pngerror.c pnggccrd.c pngget.c pngmem.c pngpread.c pngread.c pngrio.c \
           pngrtran.c pngrutil.c pngset.c pngtest.c pngtrans.c pngvcrd.c pngwio.c \
           pngwrite.c pngwtran.c pngwutil.c

ROOT    = ../..
INCLUDE =
ARCHIVE = libpng.a

default: lib

include $(ROOT)/gcc/Makefile.inc





