CPP_SRC  := plasma.cpp window.cpp
RES_SRC  := gltPlasma.rc
NAME     := gltPlasma

ROOT     = ../../..
INCLUDE  =
LIBS     = -lglutm -lglt 
                    
default: prog       

include $(ROOT)/gcc/Makefile.inc
