CPP_SRC = config.cpp main.cpp master.cpp menu.cpp raypp.cpp window.cpp \
	  timer.cpp input.cpp winexam.cpp winiv.cpp shape.cpp robot.cpp axes.cpp \
	  saver.cpp

ROOT    = ../..
INCLUDE = 
ARCHIVE = libglutm.a

default: lib

include $(ROOT)/gcc/Makefile.inc
