CPP_SRC = \
	pasync.cpp      pinfile.cpp    pipmsgsv.cpp   pnpipe.cpp      ppodlist.cpp    pstrlist.cpp   ptrigger.cpp	\
	patomic.cpp     pinfilter.cpp  pipstm.cpp     pnpserver.cpp   pputf.cpp       pstrmanip.cpp  ptypes_test.cpp	\
	pcomponent.cpp  pinmem.cpp     pipstmsv.cpp   pobjlist.cpp    prwlock.cpp     pstrtoi.cpp    punit.cpp		\
	pcset.cpp       pinstm.cpp     pipsvbase.cpp  poutfile.cpp    psemaphore.cpp  pstrutils.cpp  punknown.cpp	\
	pcsetdbg.cpp    pintee.cpp     pmd5.cpp       poutfilter.cpp  pstdio.cpp      ptextmap.cpp   pvariant.cpp	\
	pexcept.cpp     piobase.cpp    pmem.cpp       poutmem.cpp     pstrcase.cpp    pthread.cpp    pversion.cpp	\
	pfatal.cpp      pipbase.cpp    pmsgq.cpp      poutstm.cpp     pstrconv.cpp    ptime.cpp				\
	pfdxstm.cpp     pipmsg.cpp     pmtxtable.cpp  ppipe.cpp       pstring.cpp     ptimedsem.cpp

ROOT    = ../..
INCLUDE = 
ARCHIVE = libptypes.a

default: lib

include $(ROOT)/gcc/Makefile.inc





