C_SRC = \
    og_callbacks.c  og_font_data.c  og_main.c     og_stroke_mono_roman.c  og_window.c \
	og_cursor.c     og_gamemode.c   og_menu.c     og_stroke_roman.c \
	og_display.c    og_geometry.c   og_misc.c     og_structure.c \
	og_ext.c        og_init.c       og_overlay.c  og_teapot.c \
	og_font.c       og_joystick.c   og_state.c    og_videoresize.c

ROOT     = ../..
INCLUDE  = 
EXPAND    = --tabs=4

default: lib

ARCHIVE = libopenglut.a

include $(ROOT)/gcc/Makefile.inc




