C_SRC = freeglut_callbacks.c  freeglut_gamemode.c              freeglut_menu.c               freeglut_structure.c   \
	freeglut_cursor.c     freeglut_geometry.c              freeglut_misc.c               freeglut_teapot.c      \
	freeglut_display.c    freeglut_glutfont_definitions.c  freeglut_overlay.c            freeglut_videoresize.c \
	freeglut_ext.c        freeglut_init.c                  freeglut_state.c              freeglut_window.c      \
	freeglut_font.c       freeglut_joystick.c              freeglut_stroke_mono_roman.c \
	freeglut_font_data.c  freeglut_main.c                  freeglut_stroke_roman.c

ROOT     = ../..
INCLUDE  = 
EXPAND    = --tabs=2

default: lib

ARCHIVE = libfreeglut.a

include $(ROOT)/gcc/Makefile.inc




