CPP_SRC  = \
	particle.cpp trail.cpp main.cpp fade.cpp examples.cpp \
	gravity.cpp field.cpp engine.cpp lorenz.cpp recode.cpp \
	rossler.cpp project.cpp rain.cpp hockey.cpp textures.cpp \
	colmap.cpp plot.cpp window.cpp psystem.cpp document.cpp \
	integrat.cpp init.cpp network.cpp video.cpp grid.cpp

NAME     = grips
ROOT     = ../../..
INCLUDE  =
LIBS     = -lptypes -lpthread
                    
default: prog       

include $(ROOT)/gcc/Makefile.inc

