C_SRC    = adler32.c compress.c crc32.c deflate.c gzio.c \
           infback.c inffast.c inflate.c inftrees.c \
           trees.c uncompr.c zutil.c

ROOT     = ../..
INCLUDE  =
ARCHIVE  = libz.a

default: lib

include $(ROOT)/gcc/Makefile.inc





