C_SRC    = unzzip.c  zzcat.c  zzdir.c  zzip.c  zziptest.c  zzobfuscated.c  zzxorcat.c  zzxorcopy.c  zzxordir.c

ROOT     = ../../..
INCLUDE  = 

LIBS     = -lzzip

default: prog       

include $(ROOT)/gcc/Makefile.inc

