CPP_SRC  = main.cpp playback.cpp rasterb.cpp terminal.cpp textbuff.cpp
RES_SRC  = note.rc
NAME     = note

ROOT     = ../../../..
INCLUDE  =
LIBS     = -lglutm -lglt

default: prog
        
include $(ROOT)/gcc/Makefile.inc
