CPP_SRC  = draw.cpp lif2src.cpp main.cpp window.cpp world.cpp rowiter.cpp
NAME     = gltLife

ROOT     = ../../..
INCLUDE  =
LIBS     = -lglutm -lglt
                    
default: prog       

include $(ROOT)/gcc/Makefile.inc

