########################################################################
#
# Auto-detection of target platform

ifeq ($(shell uname),Linux)
TARGET = linux
endif

# In windows Cygwin mode, MingW32 mode needs to be
# explicitly enabled

ifdef WINDIR
#TARGET = mingw32
TARGET = cygwin
endif

########################################################################

CC           = gcc
CXX          = g++

VPATH        += $(ROOT)/lib

########################################################################
#
# DEBUG SYMBOLS, OPTIMISATION

CFLAGS      += -O3 -DNDEBUG
#CFLAGS     += -g
CFLAGS      += -finline-functions -ffast-math -fomit-frame-pointer -funroll-loops

#CXXFLAGS    += -O3 -DNDEBUG
CXXFLAGS   += -g
#CXXFLAGS    += -finline-functions -ffast-math -fomit-frame-pointer -funroll-loops

########################################################################
#
# COMPILER WARNINGS

CFLAGS      += -Wall
CFLAGS      += -Wno-long-long
CFLAGS      += -pedantic

CXXFLAGS    += -Wall
CXXFLAGS    += -Wno-long-long
#CXXFLAGS   += -pedantic

########################################################################
#
# GLT, ZLIB, PNG, JPEG, etc...

# C

CFLAGS       += -I$(ROOT)/src
CFLAGS       += -DPNG_STATIC
CFLAGS       += -I$(ROOT)/src/zlib
CFLAGS       += -I$(ROOT)/src/jpeg

CLIBS         = -L$(ROOT)/lib
CLIBS        += -lpng
CLIBS        += -lz
CLIBS        += -ljpeg

# C++

CXXFLAGS     += -I$(ROOT)/src
CXXFLAGS     += -DPNG_iTXt_SUPPORTED    # Used by FreeImage
CXXFLAGS     += -I$(ROOT)/src/zlib
CXXFLAGS     += -I$(ROOT)/src/jpeg
CXXFLAGS     += -I$(ROOT)/src/freeimage

CXXLIBS       = -L$(ROOT)/lib
CXXLIBS      += -lglutm
CXXLIBS      += -lglt
CXXLIBS      += -lfreeimage             # If using freeimage
CXXLIBS      += -lpng
CXXLIBS      += -lz                     # If using zLib
CXXLIBS      += -ljpeg                  # If using libjpeg

########################################################################
#
# GLUT, FREEGLUT, OPENGLUT (Only one of these)

# C

#CFLAGS      += -DGLUT_STATIC
#CLIBS       += -lglut

#CFLAGS      += -DFREEGLUT_STATIC
#CLIBS       += -lfreeglut

CFLAGS       += -DOPENGLUT_STATIC
CLIBS        += -lopenglut

# C++

#CXXFLAGS    += -DGLUT_STATIC
#CXXLIBS     += -lglut

#CXXFLAGS    += -DFREEGLUT_STATIC
#CXXLIBS     += -lfreeglut

CXXFLAGS     += -DOPENGLUT_STATIC
CXXLIBS      += -lopenglut

########################################################################
#
# CYGWIN

ifeq ($(TARGET),cygwin)
	EXE        = .exe
	CXXFLAGS  +=
	CXXLIBS   += -lglu32 -lopengl32 -lwinmm -lgdi32 -lstdc++
else

########################################################################
#
# MINGW32

ifeq ($(TARGET),mingw32)
	EXE        = .exe
	CXXFLAGS  += -mno-cygwin
	CXXLIBS   += -lglu32 -lopengl32 -lwinmm -lgdi32 -lstdc++ -mno-cygwin
else

########################################################################
#
# UNIX, LINUX

	EXE       =
	CXXLIBS  += -L/usr/X11R6/lib -lGLU -lGL -lX11 -lXmu -lstdc++
	CXXFLAGS += -I/usr/X11R6/include/
	VPATH    += /usr/X11R6/lib
endif

########################################################################

CFLAGS      += $(INCLUDE)
CXXFLAGS    += $(INCLUDE)

CLIBS       += $(LIBS)
CXXLIBS     += $(LIBS)

endif
