# User configurable options for Makefile.inc

CC        = gcc
CXX       = g++

INCLUDE   := $(INCLUDE) -DPNG_STATIC
CXXFLAGS  = -I$(ROOT)/src $(INCLUDE) -O3 -DNDEBUG -finline-functions -ffast-math -fomit-frame-pointer -funroll-loops -Wall -Wno-long-long -pedantic
#CXXFLAGS = -I$(ROOT)/src $(INCLUDE) -g -Wall -Wno-long-long -pedantic
CXXLIBS   = -L$(ROOT)/lib $(LIBS) -lpng -lz -ljpeg
CFLAGS      = $(CXXFLAGS)

# In windows Cygwin mode, MingW32 mode needs to be
# explicitly enabled

ifdef WINDIR
#	TARGET = mingw32
TARGET = cygwin
endif

# Link libraries vary slightly across Cygwin, MingW32
# and generic Unix compilation modes.

#### CYGWIN

ifeq ($(TARGET),cygwin)
	EXE        = .exe
#	CXXLIBS   += -lglut32 -lglu32 -lopengl32 -lwinmm -lgdi32 -lstdc++
	CXXLIBS   += -lfreeglut -lglu32 -lopengl32 -lwinmm -lgdi32 -lstdc++
	CXXFLAGS  := -DFREEGLUT_STATIC -I$(ROOT)/src/zlib -I$(ROOT)/src/jpeg $(CXXFLAGS)
else 

#### MINGW32

ifeq ($(TARGET),mingw32)
	EXE        = .exe
#	CXXLIBS   += -lglut32 -lglu32 -lopengl32 -lwinmm -lgdi32 -lstdc++ -mno-cygwin
	CXXLIBS   += -lfreeglut -lglu32 -lopengl32 -lwinmm -lgdi32 -lstdc++ -mno-cygwin
	CXXFLAGS  := -DFREEGLUT_STATIC -I$(ROOT)/src/zlib -I$(ROOT)/src/jpeg $(CXXFLAGS) -mno-cygwin
else 

#### UNIX

	EXE       =
	CXXLIBS  += -L/usr/X11R6/lib -lfreeglut -lGLU -lGL -lX11 -lXmu
	CXXFLAGS += -I/usr/X11R6/include/ 
endif
endif
