#!/bin/sh

printf "/* Note - this file generated by trees2.sh */\n\n#include \"trees2.h\"\n\n" > trees2.cpp
printf "#ifndef TREES2_H\n#define TREES2_H\n\n"            > trees2.h

printf "Cylinders...\n"

for i in 2 3 4 5 6 8 10 15 20 50 100
do 
	echo $i;
	cylinders $i > tmp.txt;
	printf "\nchar cylinder%dTree[] = \n"    $i >> trees2.cpp;
	printf "extern char cylinder%dTree[];\n" $i >> trees2.h;
	text2src tmp.txt >> trees2.cpp;
done

printf "\n" >> trees2.h
printf "\nCheese...\n"

for i in 10 20 30 40 50 60 70 80 90 100
do
	echo $i;
	cheese 0 0.25 1974 $i > tmp.txt
	printf "\nchar cheese%dTree[] = \n"    $i >> trees2.cpp;
	printf "extern char cheese%dTree[];\n" $i >> trees2.h;
	text2src tmp.txt >> trees2.cpp
done

printf "\n#endif\n" >> trees2.h

