CPP_SRC = mesh.cpp read3dsb.cpp sweep.cpp triangle.cpp quad.cpp vrml.cpp vrmlpars.cpp vrmlscan.cpp md3.cpp

ROOT    = ../..
INCLUDE =
ARCHIVE = libglt.a

default: lib

include $(ROOT)/gcc/Makefile.inc
