CPP_SRC  = main.cpp textures.cpp 
RES_SRC  = unifonte.rc
NAME     = unifonte

ROOT     = ../../../..
INCLUDE  =
LIBS     = -lglutm -lglt
                    
default: prog       

include $(ROOT)/gcc/Makefile.inc

