CPP_SRC = 	path.cpp matrix4.cpp plane.cpp point.cpp round.cpp vector2.cpp vector3.cpp vector4.cpp \
		bbox.cpp volume.cpp umatrix.cpp random.cpp noise.cpp real.cpp ray.cpp

ROOT    = ../..
INCLUDE =
ARCHIVE = libglt.a

default: lib

include $(ROOT)/gcc/Makefile.inc
