CPP_SRC = bin2src.cpp  dos2unix.cpp  text2src.cpp  unix2dos.cpp vrmlpars.cpp stitch.cpp

ROOT    = ../../..
INCLUDE =
LIBS    = -lglutm -lglt
                    
default: prog       

include $(ROOT)/gcc/Makefile.inc
