#
# Subdirectories are recursed in this order - be careful to
# order things according to link dependencies.  (Programs
# should go last)
#

SUBDIRS = glt misc math mesh node glutm fonts network unifont \
	  zlib zzip png jpeg glut freeglut ptypes csg glui program

ROOT    = ..
INCLUDE =

default: recurse

include $(ROOT)/gcc/Makefile.inc



